name: Multiarch build docker image

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/ronoaldo/luantiserver

jobs:
  multiarch-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            args: |-
              LUANTI_VERSION=master
              MINETEST_GAME_VERSION=master
              LUAJIT_VERSION=v2.1
            tags: |-
              5.13.0-dev
              unstable
              dev
            platforms: |-
              linux/amd64
              linux/arm64
          - dockerfile: Dockerfile
            args: |-
              LUANTI_VERSION=5.12.0
              MINETEST_GAME_VERSION=844216cbb8a8647999ed3cb858e1f0fddafea01f
              LUAJIT_VERSION=f9140a622a0c44a99efb391cc1c2358bc8098ab7
            tags: |-
              stable
              stable-5
            platforms: |-
              linux/amd64
              linux/arm64
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Luanti version/branch for Dockerfile/args
        id: luanti-version
        run: |
          export LUANTI_VERSION="$(echo "${{ matrix.args }}" | grep LUANTI_VERSION | cut -f 2 -d=)"
          export MINETEST_GAME_VERSION="$(echo "${{ matrix.args }}" | grep MINETEST_GAME_VERSION | cut -f 2 -d=)"
          echo "version=${LUANTI_VERSION}" >> $GITHUB_OUTPUT
          echo "game=${MINETEST_GAME_VERSION}" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            ${{ steps.luanti-version.outputs.version }}
            ${{ matrix.tags }}

      - name: Print calculated Docker tags
        id: build-tags-check
        shell: bash
        run: |
          echo "${{ steps.meta.outputs.tags }}"

      - name: Run integration tests on Dockerfile
        id: run-test-build
        shell: bash
        run: |
          LUANTI_VERSION=${{steps.luanti-version.outputs.version}} \
          MINETEST_GAME_VERSION=${{steps.luanti-version.outputs.game}} \
          ./test/integration-test.sh

      - name: Set up QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.args }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.ref_name == 'main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
